[pytest]
pythonpath = .
filterwarnings =
    ignore:.*SwigPy.*has no __module__ attribute:DeprecationWarning
    ignore:.*swigvarlink.*has no __module__ attribute:DeprecationWarning
    ignore:.*lossless JXL image from JPEG:UserWarning